use dbms;
CREATE TABLE AUTHOR(
Author_ID varchar(5) NOT NULL PRIMARY KEY ,
LastName text(15) NOT NULL , 
FirstName text(15) NOT NULL ,
Email text(40),
City text(15) , 
Country text(15)
);

create table BOOK(	
BOOK_ID VARCHAR(5) PRIMARY KEY CHECK(BOOK_ID LIKE "B%"),
BOOK_TITLE TEXT NOT NULL,
COPIES INT CHECK(COPIES > 2)	
);

CREATE TABLE AUTHOR_LIST(
ROLE TEXT(15),
BOOK_ID VARCHAR(5),
foreign key (BOOK_ID) references BOOK(BOOK_ID),
AUTHOR_ID VARCHAR(5),
foreign key (AUTHOR_ID) references AUTHOR(AUTHOR_ID)
, primary key(BOOK_ID,AUTHOR_ID)
);
insert INTO  AUTHOR VALUES("1","GROVER","ASHNEER","AG@XYZ.COM","DELHI","INDIA");
insert INTO  AUTHOR VALUES("2","MODI","PRATHAM","PM@XYZ.COM","AHMEDABAD","INDIA");
insert INTO  AUTHOR VALUES("3","BRUCE","WAYNE","BW@XYZ.COM","GOTHAM","USA");
insert INTO  AUTHOR VALUES("4","HOOFSTADER","LEONARD","LS@XYZ.COM","BROOKLYN","USA");

INSERT INTO BOOK VALUES ("B-101","Lord of the Rings",5),("B-102","Catcher in the Rye",12),
("B-103","Pinocchio",10),("B-104","Harry Potter and the Sorcerers Stone",25);

INSERT INTO AUTHOR_LIST VALUES("WRITTER","B-101","1");
insert INTO AUTHOR_LIST VALUES("COPYWRITTER","B-102","2");
insert INTO AUTHOR_LIST VALUES("BLOGGER","B-103","3");
insert INTO AUTHOR_LIST VALUES("STAFFWRITTER","B-104","4");

ALTER TABLE AUTHOR_LIST
ADD PUBLISHER CHAR(30);